apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeppelin-oci-pvc
spec:
  storageClassName: "oci-bv"
  accessModes:
    - ReadWriteOne
  resources:
    requests:
      storage: 50Gi
